[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
base_mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options